### GET
# GET {{apiUrl}}/resources/permissions?id=2ff3e024-9d34-4a9d-a6af-ff5008db3850&limit=1&sort=createdAt&include=role.permissions
GET {{apiUrl}}/resources/permissions?include=roles
Content-Type: application/json
Authorization: Bearer {{token}}

### GET ONE
GET {{apiUrl}}/resources/permissions/2ff3e024-9d34-4a9d-a6af-ff5008db3850?include=roles
Content-Type: application/json
Authorization: Bearer {{token}}

### CREATE
POST {{apiUrl}}/resources/permissions
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "email": "12345678@fasf.com",
  "password": "gkjvsdhgsd"
}

### UPDATE
PATCH {{apiUrl}}/resources/permissions/2ff3e024-9d34-4a9d-a6af-ff5008db3850
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "password": "6Mahoney9!"
}

### DELETE
DELETE {{apiUrl}}/resources/permissions/2ff3e024-9d34-4a9d-a6af-ff5008db3850
Content-Type: application/json
Authorization: Bearer {{token}}
