version: "3"
services:
  # node:
  #   build:
  #     context: ./api
  #     dockerfile: Dockerfile
  #   image: notifyapp/api
  #   user: "node"
  #   working_dir: /home/node/app
  #   environment:
  #     - NODE_ENV=development
  #   volumes:
  #     - ./api:/home/node/app
  #   ports:
  #     - 8880:8880
  #     - 9229:9229
  #   command: "npm run start:debug"
  maildev:
    image: maildev/maildev
    restart: always
    ports:
      - 8889:8889
      - 8888:8888
    environment:
      MAILDEV_WEB_PORT: 8889
      MAILDEV_SMTP_PORT: 8888

  db:
    image: postgres:16.2
    restart: always
    volumes:
      - microrisdb:/var/lib/postgresql/data/
    ports:
      - 8881:5432
    environment:
      POSTGRES_DB: microrisdb
      POSTGRES_USER: microrisdbusr
      POSTGRES_PASSWORD: 6mahoney9!

volumes:
  microrisdb:
