### GET
GET {{host}}/resources/users?limit=3&sort=createdAt&include=role.permissions
Content-Type: application/json
Authorization: Bearer {{token}}

### GET ONE
GET {{host}}/resources/users/463c80fa-9c85-42cc-86a2-3d7177c0d819?include=role.permissions,info
Content-Type: application/json
Authorization: Bearer {{token}}

### CREATE
POST {{host}}/resources/users
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "email": "fsafafasf@fafa.com",
  "password": "1234567"
}

### UPDATE
PATCH {{host}}/resources/users/463c80fa-9c85-42cc-86a2-3d7177c0d819
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "password": "6Mahoney9!"
}

### DELETE
DELETE {{host}}/resources/users/463c80fa-9c85-42cc-86a2-3d7177c0d819
Content-Type: application/json
Authorization: Bearer {{token}}
