### GET
GET {{apiUrl}}/resources/users?limit=3&sort=createdAt&include=role.permissions
Content-Type: application/json
Authorization: Bearer {{token}}

### GET ONE
GET {{apiUrl}}/resources/users/8b0ebe5d-f496-44b7-9790-1951e6a7df21?include=role.permissions,info
Content-Type: application/json
Authorization: Bearer {{token}}

### CREATE
POST {{apiUrl}}/resources/users
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "email": "test@test.com",
  "password": "123456"
}

### UPDATE
PATCH {{apiUrl}}/resources/users/8b0ebe5d-f496-44b7-9790-1951e6a7df21
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "email": "testaaa354f@test.coms"
}

### DELETE
DELETE {{apiUrl}}/resources/users/8b0ebe5d-f496-44b7-9790-1951e6a7df21
Content-Type: application/json
Authorization: Bearer {{token}}
