### GET
GET {{apiUrl}}/resources/test?include=role.permissions,info
Content-Type: application/json
Authorization: Bearer {{token}}

### GET ONE
GET {{apiUrl}}/resources/test/fe84fe43-7b96-4b87-804b-d3f0c8219bcb?include=role.permissions,info
Content-Type: application/json
Authorization: Bearer {{token}}

### CREATE
POST {{apiUrl}}/resources/test
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "email": "testfsfasfa@test.com",
  "password": "123456"
}

### UPDATE
PATCH {{apiUrl}}/resources/test/fe84fe43-7b96-4b87-804b-d3f0c8219bcb
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "email": "testaaa354f@test.coms"
}

### DELETE
DELETE {{apiUrl}}/resources/test/fe84fe43-7b96-4b87-804b-d3f0c8219bcb
Content-Type: application/json
Authorization: Bearer {{token}}

### GET RELATIONSHIP
GET {{apiUrl}}/resources/test/fe84fe43-7b96-4b87-804b-d3f0c8219bcb/relations/info
Content-Type: application/json
Authorization: Bearer {{token}}