### GET
# GET {{apiUrl}}/roles?id=6edfc9a3-98f5-448b-9386-9c75faf24c1d&limit=1&sort=createdAt&include=role.permissions
GET {{apiUrl}}/roles?include=permissions
Content-Type: application/json
Authorization: Bearer {{token}}

### GET ONE
GET {{apiUrl}}/roles/6edfc9a3-98f5-448b-9386-9c75faf24c1d?include=permissions
Content-Type: application/json
Authorization: Bearer {{token}}

### CREATE
POST {{apiUrl}}/roles
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "email": "12345678@fasf.com",
  "password": "gkjvsdhgsd"
}

### UPDATE
PATCH {{apiUrl}}/roles/6edfc9a3-98f5-448b-9386-9c75faf24c1d
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "password": "6Mahoney9!"
}

### DELETE
DELETE {{apiUrl}}/roles/6edfc9a3-98f5-448b-9386-9c75faf24c1d
Content-Type: application/json
Authorization: Bearer {{token}}

### GET ROLE PERMISSIONS
GET {{apiUrl}}/roles/6edfc9a3-98f5-448b-9386-9c75faf24c1d/permissions?filter[]=name||$eq||resources.users.update
Content-Type: application/json
Authorization: Bearer {{token}}
