### GET
# GET {{host}}/resources/roles?id=003fd571-2dee-416c-9cb9-44b1c9a093b5&limit=1&sort=createdAt&include=role.permissions
GET {{host}}/resources/roles?include=permissions
Content-Type: application/json
Authorization: Bearer {{token}}

### GET ONE
GET {{host}}/resources/roles/d1a956ee-a1bb-4bee-ab49-0d83eecc235c?include=permissions
Content-Type: application/json
Authorization: Bearer {{token}}

### CREATE
POST {{host}}/resources/roles
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "email": "12345678@fasf.com",
  "password": "gkjvsdhgsd"
}

### UPDATE
PATCH {{host}}/resources/roles/003fd571-2dee-416c-9cb9-44b1c9a093b5
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "password": "6Mahoney9!"
}

### DELETE
DELETE {{host}}/resources/roles/003fd571-2dee-416c-9cb9-44b1c9a093b5
Content-Type: application/json
Authorization: Bearer {{token}}
